bookland/urls.py
from django.urls import path
from caveguskov import views
from django.urls import include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
# from django.conf.urls import url

from . import views, views_eng


app_name = 'bookland'


urlpatterns = [
    path('', views.index, name='index'),
    path('eng/', views_eng.index_eng, name='index_eng'),

    path('list/seites/<topic>', views.seites, name='seites'),
    path('eng/list/seites/<topic>', views_eng.seites_eng, name='seites_eng'),

    path('seites/<topic> <pk>', views.seites_list, name='seites-list'),
    path('eng/seites/<topic> <pk> ', views_eng.seites_list_eng, name='seites-list_eng'),

    path('zoom/<pk>/<quelle>', views.zoom_seite, name='zoom'),
    path('eng/zoom/<pk>/<quelle>', views_eng.zoom_seite_eng, name='zoom_eng'),

    path('register/<art>', views.register_art, name='register-art'),
    path('eng/register/<art>', views_eng.register_art_eng, name='register-art_eng'),

    path('register/object/<obj>', views.register_object, name='register-object'),
    path('eng/register/object/<obj>', views_eng.register_object_eng, name='register-object_eng'),

    path('register/seites/<pk_top> <pk_site>', views.register_seites, name='register-seites'),
    path('eng/register/seites/<pk_top> <pk_site>', views_eng.register_seites_eng, name='register-seites_eng'),

    path('dictionary/<dict_lang>', views.dictionary, name='dictionary'),
    path('eng/dictionary/<dict_lang>', views.dictionary, name='dictionary_eng'),

]

caveguskov/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('bookland/', include('bookland.urls')),
    path('', RedirectView.as_view(url='/bookland/', permanent=True)),
]

bookland/models.py
from django.db import models

# ========================= OBJECT =======
class Object_typ(models.Model):
    class Meta:
        ordering = ["ukr", ]

    ukr = models.CharField(max_length=50, null=True, blank=True)
    eng = models.CharField(max_length=50, null=True, blank=True)
    ita = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return str(self.ukr + '    ' + self.eng)

# ========================= BOOKSEITES =======
class Bookseites(models.Model):
    class Meta:
        ordering = ["image_seites"]
    seites = models.CharField(max_length=10,)
    image_seites = models.CharField(max_length=30, null=True, blank=True)
    name_step = models.CharField(max_length=1, null=True, blank=True)
    control = models.CharField(max_length=5, null=True, blank=True)
    name_seites1 = models.CharField(max_length=100, null = True, blank = True)
    name_seites = models.CharField(max_length=100, null = True, blank = True)
    content_seite = models.TextField(null = True, blank = True)

    name_eng1 = models.CharField(max_length=100, null=True, blank=True)
    name_eng = models.CharField(max_length=100, null=True, blank=True)
    content_eng = models.TextField(null=True, blank=True)
    contr = models.CharField(max_length=5, null = True, blank = True)


    def __str__(self):
        return str(self.seites + ' ' + self.name_seites)

    # def get_absolute_url(self):
    #     return reverse('poems:genre-detail', args=[str(self.id)])

# ========================= REGISTER =======
class Register(models.Model):
    class Meta:
        ordering = ["reg_art", "reg_f_name"]
    reg_art = models.CharField(max_length=30,)
    reg_f_name = models.CharField(max_length=100, null = True, blank = True)
    reg_f_eng = models.ForeignKey('Register_eng', on_delete=models.SET_NULL, null=True)
    reg_s_name = models.CharField(max_length=100, null=True, blank=True)
    object_typ = models.ManyToManyField(Object_typ, )
    reg_numbers = models.CharField(max_length=100, null=True, blank=True)
    reg_seites = models.ManyToManyField(Bookseites,)

    def __str__(self):
        return str(self.reg_f_name)

    # def get_absolute_url(self):
    #     return reverse('poems:genre-detail', args=[str(self.id)])

# ========================= BOOKSEITES_ENG =======
class Bookseites_eng(models.Model):
    class Meta:
        ordering = ["image_seites"]
    seites = models.CharField(max_length=10,)
    name_seites1 = models.CharField(max_length=100, null = True, blank = True)
    name_seites = models.CharField(max_length=100, null = True, blank = True)
    name_step = models.CharField(max_length=1, null = True, blank = True)
    image_seites = models.CharField(max_length=30, null = True, blank = True)
    content_seite = models.TextField(null = True, blank = True)

    def __str__(self):
        return str(self.seites + ' ' + self.name_seites)

    # def get_absolute_url(self):
    #     return reverse('poems:genre-detail', args=[str(self.id)])

# ========================= REGISTER =======
class Register_eng(models.Model):
    class Meta:
        ordering = ["reg_art", "reg_f_name"]

    reg_art = models.CharField(max_length=30, )
    reg_f_name = models.CharField(max_length=100, null=True, blank=True)
    reg_s_name = models.CharField(max_length=100, null=True, blank=True)
    object_typ = models.ManyToManyField(Object_typ, )
    reg_numbers = models.CharField(max_length=100, null=True, blank=True)
    reg_seites = models.ManyToManyField(Bookseites, )


    def __str__(self):
        return str(self.reg_art + ', ' + self.reg_f_name)

# ========================= TEXT =======
class Text_site(models.Model):

    theme = models.CharField(max_length=100, null=True, blank=True)
    ukr = models.TextField(null = True, blank = True)
    eng = models.TextField(null=True, blank=True)
    ita = models.TextField(null=True, blank=True)

    def __str__(self):
        return str(self.theme)

bookland/views.py
from django.shortcuts import render

from django.views import generic
from django.db.models import Q

from . models import Bookseites, Register, Text_site, Object_typ




# ================== INDEX  ===========================
def index(request):
    tytle = Text_site.objects.get(theme = "index_tytle")
    text_tytle = tytle.ukr
    annotation = Text_site.objects.get(theme="index_annotation")
    text_annotation = annotation.ukr


    return render(
        request, 'index.html',
        context = {
            'template': "base_generic.html",
            'language': "UKR",
            'eng': "англійська",
            'ukr': "українська",

            'text_tytle': text_tytle,
            'text_annotation': text_annotation,
        }
           )
# ================== SEITES  ===========================
def seites(request, topic):
    if topic == "1":
        seites = Bookseites.objects.all()
        bookcontents = "Зміст книги"
    else:
        seites = Bookseites.objects.all().filter(Q(name_eng1=topic) | Q(name_seites1=topic))
        bookcontents = "Зміст розділу"
        topic_menu = [[]]
        for item in seites:
            t = []
            t.append(0)
            t.append(item.name_seites1)     #1
            t.append(item.name_seites)      #2
            topic_menu.append(t)
        topic = topic_menu[1][1]

    seites_list = [[]]
    for item in seites:
        m = []
        m.append(0)
        m.append(item.name_seites1)  # 1
        m.append(item.name_seites)  # 2
        m.append(item.seites)  # 3
        m.append(item.id)  # 4
        m.append(item.name_step)  # 5
        seites_list.append(m)
    seites_list = seites_list[1:]

    section = Bookseites.objects.all().filter(name_step = "1")

    section_list = [[]]
    for item in section:
        s = []
        s.append(0)
        s.append(item.name_seites1)     #1
        if ": печерне місто" in item.name_seites1:
            s.append("___")               #2
        else:
            s.append("")                 #2
        section_list.append(s)


    return render(
        request, 'seites.html',
        context = {
            'template': "base_generic.html",
            'url_topic': "bookland:seites",
            'url_seiteslist': "bookland:seites-list",
            'language': "UKR",
            'eng': "англійська",
            'ukr': "українська",

            'seittopic': "Перегляд сторінок Книги",
            'bookcontents': bookcontents,
            'seites_list': seites_list,
            'section_list': section_list,
            'topic': topic, 'seites': seites,
            'name': 1,
            'illustration': "Світанок у миса Куле-бурун (місцевість Мангуп)"
                  }
           )

# ================== END seites  ===========================

# ================== SITES_LIST  ===========================
def seites_list(request, topic, pk):
    pk_s = Bookseites.objects.get(pk = pk)
    pk_site = pk_s.image_seites

    if topic == "1":
        seites = Bookseites.objects.all().filter(image_seites__gte=pk_site)[:10]
        menu = Bookseites.objects.all()
        bookcontents = "Зміст книги"
    else:
        seites = Bookseites.objects.all().filter(
            Q(name_eng1=topic, image_seites__gte=pk_site) | Q(name_seites1=topic, image_seites__gte=pk_site))[:10]
        menu = Bookseites.objects.all().filter(Q(name_eng1=topic) | Q(name_seites1=topic))
        bookcontents = "Зміст розділу"

    seites_list = [[]]
    for item in seites:
        m = []
        m.append(0)
        m.append(item.name_seites1)  # 1
        m.append(item.name_seites)  # 2
        m.append(item.seites)  # 3
        m.append(item.id)  # 4
        m.append(item.image_seites)  # 5
        seites_list.append(m)
    seites_list = seites_list[1:]

    seites_menu = [[]]
    for item in menu:
        m = []
        m.append(0)
        m.append(item.name_seites1)  # 1
        m.append(item.name_seites)  # 2
        m.append(item.seites)  # 3
        m.append(item.id)  # 4
        m.append(item.name_step)  # 5
        seites_menu.append(m)
    seites_menu = seites_menu[1:]



    max_seit = len(seites)
    seit_max = seites[max_seit - 1].id
    if max_seit == 1:
        text = "ОСТАННЯ СТОРІНКА виборки"
    else:
        text = "ДАЛІ - наступні сторінки ... "


    return render(
        request, 'seites_list.html',
        context = {
            'template': "base_generic.html",
            'url_seiteslist': "bookland:seites-list",
            'url_zoom': "bookland:zoom",
            'language': "UKR",
            'eng': "англійська", 'ukr': "українська",

            'seites_list': seites_list,
            'seites_menu': seites_menu,
            'seit_max': seit_max,
            'text': text, 'site': "стор.", 'zoom': "Збільшити/Переклад",
            'bookcontents': bookcontents,
            'seit_pk': pk, 'topic': topic,
        }
           )
# ================== END seites_list  ===========================

# ================== ZOOM_SEITE  ===========================
def zoom_seite(request, pk, quelle):

    seite = Bookseites.objects.get(pk = pk)

    zoom_seite = []

    zoom_seite.append(0)
    zoom_seite.append(seite.name_seites1)   #1
    zoom_seite.append(seite.name_seites)    #2
    zoom_seite.append(seite.content_seite)  #3
    zoom_seite.append(seite.image_seites)   #4
    zoom_seite.append(seite.name_seites)    #5

    topic = seite.name_seites1
    name = seite.name_seites
    return render(
        request, 'zoom_seite.html',
        context = {
            'template': "base_generic.html",
            'url_zoom': "bookland:zoom",
            'url_seiteslist': "bookland:seites-list",
            'url_register': "bookland:register-seites",
            'language': "UKR",
            'eng': "англійська", 'ukr': "українська",

            'zoom_seite': zoom_seite, 'seite_id': pk,
            'quelle_zoom': quelle, 'topic': topic,
            'back': "Назад",  'name': name,

        }
           )

# ================== END zoom_seite  ===========================

# ================== REGISTER ART ===========================
def register_art(request, art):

    if art == "1":
        art_key = "Географічні назви"
        art_name = "Географічні назви"
    if art == "2":
        art_key = "Населені пункти"
        art_name = "Населені пункти"
    if art == "3":
        art_key = "Туристичні об'єкти"
        art_name = "Туристичні об'єкти"

    reg_name_list = Register.objects.all().filter(reg_art=art_key)
    num_name = len(reg_name_list)

    art_object = set(())
    for object in reg_name_list:
        art_object.add(object.reg_s_name)

    art_object_num = [[], ]
    for item in art_object:
        l = []
        l.append(0)
        l.append(item)
        l.append(len(Register.objects.all().filter(reg_s_name=item)))

        art_object_num.append(l)

    art_object_num.sort()

    return render(
        request, 'register_art.html',
        context = {
            'template': "base_generic.html",
            'url_object': "bookland:register-object",
            'url_register': "bookland:register-seites",
            'language': "UKR",
            'eng': "англійська", 'ukr': "українська",

            'art': art, 'art_name': art_name,
            'reg_name_list': reg_name_list,
            'num_name': num_name,

            'art_object': art_object,
            'art_object_num': art_object_num,
            'illustration': "Світанок у миса Куле-бурун (місцевість Мангуп)",


        }
           )
# ================== END register_art ===========================

# ================== REGISTER OBJECT ===========================
def register_object(request, obj,):

    typ_list = Object_typ.objects.get(Q(ukr=obj) | Q(eng=obj))
    object_name = typ_list.ukr

    # object_name = obj  # обраний тип об'єкту
    reg_name_list = Register.objects.all().filter(reg_s_name = object_name)  # список об'ектів обраного типу
    num_name = len(reg_name_list)   # кількість об'ектів обраного типу

    art = reg_name_list [0].reg_art    # вид показчика (географія, міста, туроб'єкти)
    reg_name_list_all = Register.objects.all().filter(reg_art=art)   # список найменувань виду показчика
    num_name_art = len(reg_name_list_all)  # кількість найменувань виду показчика

# формування списку типів об'єктів показчика з вичисленням кількості об'єктів у списку
    art_object = set(())
    for object in reg_name_list_all:
        art_object.add (object.reg_s_name)

    art_object_num = [[],]
    for item in art_object:
        l = []
        l.append(0)
        l.append(item)
        l.append(len(Register.objects.all().filter(reg_s_name=item)))
        art_object_num.append(l)
    art_object_num.sort()

    return render(
        request, 'register_object.html',
        context = {
            'template': "base_generic.html",
            'url_object': "bookland:register-object",
            'url_register': "bookland:register-seites",
            'language': "UKR",
            'eng': "англійська", 'ukr': "українська",

            'object_name': object_name,
            'reg_name_list': reg_name_list,
            'num_name': num_name,
            'art': art,
            'num_name_art': num_name_art,
            'art_object': art_object,
            'art_object_num': art_object_num,
            'illustration': "Світанок у миса Куле-бурун (місцевість Мангуп)",

        }
           )
# ================== END register_object ===========================

# ================== REGISTER SEITES ===========================
def register_seites(request, pk_top, pk_site):
    # pk_top - id об'єкта Регистру!
    # pk_site - id сторінки з ЦУМу!

    reg_seites = Register.objects.get(pk = pk_top) # записи сторінок з вказаним об'єктом pk
    reg_name = reg_seites.reg_f_name           # найменування об'єкту
    reg_numbers =  reg_seites.reg_numbers      # нумера сторінок з вказаним об'єктом
    reg_art =  reg_seites.reg_art              # вид показчика об'єкта

bookland/templates/base_generic.html
<!--TEMPLATE CAVECITIES-->

<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Title</title>{% endblock %}

    <meta charset="utf-8">
    <!-- Responsibilaty -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Сompiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Сompiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
    table, th, td {
          border: 0px solid white;
          vertical-align: top;
          color: yellow;
        }

    .side_left {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:0.0%;       top:0%;
        width: 13.0%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }

     .content {
        background: rgb(175, 175, 200);
        border: 0px solid black;
        position: absolute;
        left:13.15%;       top:0px;
        width: 62.65%;   height: 98.0%;
        padding-left: 20;
     }

    .side_right {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:76.0%;       top:0px;
        width: 24.0%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }

    .menu {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:2.0%;       top:0.0%;
        width: 97%;   height:;
        padding-left: 0;
        list-style: none;
        color: yellow;
    }
    .copy_right {
        border: 0px solid black;
        position: absolute;
        left:7.0%;       top:86.0%;
        color: yellow;
    }

    </style>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles_cave.css' %}">

</head>

<body>

      {% block sidebar %}
<div class="side_left">

      <img src="{% static 'image/Kule1_left.jpg' %}" alt="Chatyrdag_left"
                 style="width:100%;height:100%;"/>

      <div class="menu">
           <h4><b>&nbsp;Головне меню</b></h4>

<table style="width: 101.0%; line-height: 1.2; vertical-align: baseline;" >
    <tr>
        <td style="width:17.0%; font-size: 14px" >
            <a href="{% url 'bookland:index'  %}"><strong>[X]</strong></a> </td>
        <td style="width:2.0%">&nbsp;</td>
        <td align="left" style = "font-size: 15px"><b> Домашня </b></td>
   </tr>
    <tr>
        <td> <a href="{% url 'bookland:seites' 1 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Сторінки Книги </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art' 1 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Географічні назви </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art' 2 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Населені пункти </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art' 3 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Туристичні об'єкти </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:dictionary' 1 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Словник </b></td>
   </tr>
</table>

    </div>  <!-- menu -->



      <div class="copy_right">

          <p style="line-height: 50%; font-size: 12px;">
              <b> &#169 Анатолій Гуськов </b> </p>
          <p style="line-height: 50%; font-size: 11px;">
              &nbsp;&nbsp;&nbsp;&nbsp;Версія: Червень 2022  </p>
          <p style="line-height: 50%; font-size: 11px;">
              &nbsp;&nbsp;&nbsp;&nbsp;dkgb@i.ua </p>
          <p style="line-height: 50%; font-size: 11px;">
             &nbsp;&nbsp;+380 97 760 4885 </p>
      </div>  <!-- copy_right  -->


</div> <!-- side_left -->

<div class="side_right">
    <img src="{% static 'image/Kule3_right.jpg' %}" alt="Chatyrdag_right"
                 style="width:100%;height:100%;"/>


</div> <!-- side_right -->

 {% endblock %} <!-- sidebar -->

<div class="content">
      {% block content %}

<img src="{% static 'image/Kule2_center.jpg' %}" alt="Kuleburun_center"
                 style="width:100%;height:100%;"/>

      {% endblock %}
</div> <!-- content -->



<!--</div>  &lt;!&ndash; container-fluid &ndash;&gt;-->

</body>

</html>

bookland/templates/base_generic_eng.html
<!--TEMPLATE CAVECITIES-->

<!DOCTYPE html>
<html lang="en">

<head>

    {% block title %}<title>Title</title>{% endblock %}

    <meta charset="utf-8">
    <!-- Responsibilaty -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Сompiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Сompiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style>
    table, th, td {
          border: 0px solid white;
          vertical-align: top;
          color: yellow;
        }

    .side_left {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:0.0%;       top:0%;
        width: 13.0%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }

     .content {
        background: rgb(175, 175, 200);
        border: 0px solid black;
        position: absolute;
        left:13.15%;       top:0px;
        width: 62.65%;   height: 98.0%;
        padding-left: 20;
     }

    .side_right {
        background: yellow;
        border: 0px solid black;
        position: absolute;
        left:76.0%;       top:0px;
        width: 24.0%;   height: 98.0%;
        padding-left: 0;
        list-style: none;
    }

    .menu {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:2.0%;       top:0.0%;
        width: 97%;   height:;
        padding-left: 0;
        list-style: none;
        color: yellow;
    }
    .copy_right {
        border: 0px solid black;
        position: absolute;
        left:7.0%;       top:86.0%;
        color: yellow;
    }

    </style>

    <!-- Добавление дополнительного статического CSS файла -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/styles_cave.css' %}">

</head>

<body>

      {% block sidebar %}
<div class="side_left">

      <img src="{% static 'image/Kule1_left.jpg' %}" alt="Chatyrdag_left"
                 style="width:100%;height:100%;"/>

      <div class="menu">
           <h4><b>&nbsp;Main menu</b></h5>

<table style="width: 101.0%; line-height: 1.2; vertical-align: baseline;" >
    <tr>
        <td style="width:17.0%; font-size: 14px" >
            <a href="{% url 'bookland:index_eng'  %}"><strong>[X]</strong></a> </td>
        <td style="width:2.0%">&nbsp;</td>
        <td align="left" style = "font-size: 15px"><b> Homesite </b></td>
   </tr>
    <tr>
        <td> <a href="{% url 'bookland:seites_eng' 1 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Bookpages </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art_eng' 1 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Geography </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art_eng' 2 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Settlements </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:register-art_eng' 3 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Tourist Objects </b></td>
   </tr>
   <tr>
        <td> <a href="{% url 'bookland:dictionary' 2 %}"><strong>[X]</strong></a> </td>
        <td> </td>
        <td style = "font-size: 15px"><b> Dictionary </b></td>
   </tr>
</table>

    </div>  <!-- menu -->



      <div class="copy_right">

          <p style="line-height: 50%; font-size: 12px;">
              <b> &#169 Anatoliy Guskov </b> </p>
          <p style="line-height: 50%; font-size: 11px;">
              &nbsp;&nbsp;&nbsp;&nbsp;Version: Juni 2022  </p>
          <p style="line-height: 50%; font-size: 11px;">
              &nbsp;&nbsp;&nbsp;&nbsp;dkgb@i.ua </p>
          <p style="line-height: 50%; font-size: 11px;">
             &nbsp;&nbsp;+380 97 760 4885 </p>
      </div>  <!-- copy_right  -->


</div> <!-- side_left -->

<div class="side_right">
    <img src="{% static 'image/Kule3_right.jpg' %}" alt="Chatyrdag_right"
                 style="width:100%;height:100%;"/>


</div> <!-- side_right -->

 {% endblock %} <!-- sidebar -->

<div class="content">
      {% block content %}
 <div class = "copyright">
     <p><b>001</b>Світанок у миса Куле-бурун (місцевість Мангуп)</p>
 </div>
      {% endblock %}
</div> <!-- content -->



<!--</div>  &lt;!&ndash; container-fluid &ndash;&gt;-->

</body>

</html>

bookland/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>



    <style>
    table, th, td {
          border: 0px solid white;
          vertical-align: top;
          color: yellow;
        }

     .content {
        background: rgb(175, 175, 200);
        border: 0px solid black;
        position: absolute;
        left:13.15%;       top:0px;
        width: 62.65%;   height: 99.5%;
        padding-left: 20;
    }

    .tytle {
        background: none;
        border: 0px solid black;
        position: absolute;
        left:0.0%;       top:-2.0%;
        width: 90.0%;   height: 88.0%;
        padding-left: 20;
        overflow: none;
        color: yellow;
        line-height: 1.1;
    }

    .side_right_text {
        background: none;
        border: 0px solid black;
        white-space: pre-line;
        overflow-y: auto; /* Add vertical scrollbar */
        position: absolute;
        left: 101.5%;       top:18.0%;
        width: 37.0%;   height: 80.0%;
        color: white;
    }


    </style>

    <meta charset="UTF-8">
    <title>Land of the Caves Cities</title>


</head>
<body>

{% extends template %}
{% load static %}

 {% block content %}

    <div class="bottom-left">
        <p style = "color: white"><b> {{ language }} </b></p>
        <a class="button" href="{% url 'bookland:index' %}">&nbsp;{{ukr}}&nbsp;</a> <br>
        <a class="button" href="{% url 'bookland:index_eng' %}">&nbsp;{{eng}}&nbsp;&nbsp;&nbsp;</a>
    </div> <!-- bottom-left -->


    <img src="{% static 'image/tytle.jpg' %}" alt="Tytle"
         style="width:100%; height:100%;"/>

    <pre class = "tytle"><b>
    {{ text_tytle }} </b>
    </pre>

<p class = "side_right_text" style = "font-size: 12px; line-height: 1.2;">
    {{ text_annotation }}
</p>

    {% endblock %}